using System.Text;
using System.Text.Json;
using OtpBar.Core;
using static OtpBarTests.TestSupport;

namespace OtpBarTests;

public class TotpTests
{
    [Fact]
    public void Rfc6238All18Vectors()
    {
        // RFC 6238 Appendix B: expected values are published, not generated by our code.
        double[] times = [59, 1111111109, 1111111111, 1234567890, 2000000000, 20000000000];
        string[][] expected =
        [
            ["94287082", "07081804", "14050471", "89005924", "69279037", "65353130"],
            ["46119246", "68084774", "67062674", "91819424", "90698825", "77737706"],
            ["90693936", "25091201", "99943326", "93441116", "38618901", "47863826"]
        ];
        var seeds = JsonSerializer.Deserialize<string[]>(Fixture("rfc-seeds"))!;
        OtpAlgorithm[] algorithms = [OtpAlgorithm.Sha1, OtpAlgorithm.Sha256, OtpAlgorithm.Sha512];

        for (var index = 0; index < algorithms.Length; index++)
        {
            var entry = new OtpEntry("RFC", seeds[index], algorithm: algorithms[index], digits: 8);
            for (var timeIndex = 0; timeIndex < times.Length; timeIndex++)
            {
                var code = Totp.Generate(entry, times[timeIndex]);
                Assert.Equal(expected[index][timeIndex], code.Value);
                Assert.Equal((Math.Floor(times[timeIndex] / 30) + 1) * 30, code.ValidUntilUnixSeconds);
            }
        }
    }

    [Fact]
    public void AllSupportedParametersAgainstNodeOpenSsl()
    {
        var vectors = JsonSerializer.Deserialize<Vector[]>(
            Fixture("totp-matrix"),
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true })!;
        Assert.Equal(288, vectors.Length);

        foreach (var vector in vectors)
        {
            Assert.True(OtpAlgorithmNames.TryParse(vector.Algorithm, out var algorithm));
            var entry = new OtpEntry(
                "Matrix", PublicTestSecret, algorithm: algorithm, digits: vector.Digits, period: vector.Period);
            var code = Totp.Generate(entry, vector.Timestamp);
            Assert.Equal(vector.Code, code.Value);
            Assert.Equal(vector.Digits, code.Value.Length);
            Assert.True(code.ValidUntilUnixSeconds > vector.Timestamp);
        }
    }

    [Fact]
    public void Base32PublishedRfc4648Examples()
    {
        (string Encoded, string Plaintext)[] examples =
        [
            ("MY======", "f"), ("MZXQ====", "fo"), ("MZXW6===", "foo"),
            ("MZXW6YQ=", "foob"), ("MZXW6YTB", "fooba"), ("MZXW6YTBOI======", "foobar")
        ];
        foreach (var (encoded, plaintext) in examples)
        {
            Assert.Equal(Encoding.UTF8.GetBytes(plaintext), Base32.Decode(Base32.Canonical(encoded)));
        }
        Assert.Equal("MZXW6YTBOI", Base32.Canonical("mzxw 6ytb oi======\n"));
    }

    [Theory]
    [InlineData("")]
    [InlineData("A")]
    [InlineData("ABC")]
    [InlineData("ABCDEF")]
    [InlineData("M1======")]
    [InlineData("M0======")]
    [InlineData("MY=")]
    [InlineData("MY=======")]
    [InlineData("MY======A")]
    [InlineData("MZ======")]
    [InlineData("密钥")]
    public void InvalidBase32IsRejected(string secret) =>
        Throws(OtpErrorKind.InvalidSecret, () => new OtpEntry("Invalid", secret));

    [Fact]
    public void InvalidParametersAndTimeAreRejected()
    {
        foreach (var digits in new[] { 0, 4, 9, int.MaxValue })
        {
            Throws(OtpErrorKind.InvalidParameters, () => new OtpEntry("Invalid", PublicTestSecret, digits: digits));
        }
        foreach (var period in new[] { 0, -30, 15, int.MaxValue })
        {
            Throws(OtpErrorKind.InvalidParameters, () => new OtpEntry("Invalid", PublicTestSecret, period: period));
        }
        Throws(OtpErrorKind.InvalidName, () => new OtpEntry(" \n ", PublicTestSecret));

        var entry = new OtpEntry("Valid", PublicTestSecret);
        foreach (var timestamp in new[] { -1, double.NaN, double.PositiveInfinity, double.MaxValue })
        {
            Throws(OtpErrorKind.InvalidTime, () => Totp.Generate(entry, timestamp));
        }
    }

    [Fact]
    public void DescribingAnEntryNeverSpellsOutTheSecret()
    {
        // The description reaches accessibility tools, logs and debuggers.
        var described = new OtpEntry("GitHub", PublicTestSecret, account: "me@example.invalid").ToString();

        Assert.DoesNotContain(PublicTestSecret, described, StringComparison.OrdinalIgnoreCase);
        Assert.Equal("GitHub (me@example.invalid)", described);
        Assert.Equal("GitHub", new OtpEntry("GitHub", PublicTestSecret).ToString());
    }

    private sealed record Vector(string Algorithm, int Digits, int Period, double Timestamp, string Code);
}
